version: 2.1

commands:
  print_pipeline_id:
    description: prints the Circle CI Workflow ID
    parameters:
      steps:
        - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  myjob:
    docker:
    - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id


workflows:
  my_workflow:
    jobs:
      - myjob